// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`
  STARTUP

  AUTH_CHANGE

  LOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE

  LOGOUT_ATTEMPT
  LOGOUT_SUCCESS
  LOGOUT_FAILURE

  REGISTER_ATTEMPT
  REGISTER_SUCCESS
  REGISTER_FAILURE

  USER_SETTINGS_RECEIVED
  USER_UPDATES_RECEIVED
  USER_RECEIVED

  ACTIVE_USERS_RECEIVED

  SET_ACTIVE_CATEGORY

  GET_MSG_AUDIO
  RECEIVED_MSG_AUDIO
  RECEIVED_MSG_ERROR
`)
